[package]
name = "clighlighter"
version = "0.3.0"
edition = "2024"

[build-dependencies]
cc = "*"

[dependencies]
clap = { version = "4.5.27", features = ["cargo", "derive"] }
tree-sitter = "0.25.1"
tree-sitter-rust = "0.23.2"
tree-sitter-typescript = "0.23.2"
